### ISSUE TITLE
Proposed RFC Feature: Remote O3DE objects

### ISSUE THREAD

**Issue by AMZN-Phil** [o3de/sig-content#54]
### Summary

Sharing work, for example Projects that rely on external gems, or Templates is currently a manual process of gathering the required objects and registering them with the O3DE engine. A system to download Gems from O3DE repositories currently exist, extending this to all object types, and being able to gather dependencies from repositories would simplify the sharing of projects and other O3DE objects.

### What is the relevance of this feature?

Having a way to easily share Projects/Gems/Templates that users create without this feature requires a user to download the required objects, extract the files to a location and register them using the O3DE CLI, which requires knowledge of the correct arguments. Currently it is possible to add an O3DE repository which contains downloadable gems, and download and register the Gems through the Project Manager UI. Extending this to work with Projects and Templates means it would also be possible to download Projects and Templates through the Project Manager, including having a repository containing Gems, Projects and Templates. This means that a repository could contain a Gem and a sample project, all accessable and downloadable through the Project Manager UI simplifying the process of exploring new projects and gems. As with the way Project Manager works for current features, this will be implemented in Python with Project Manager being a simple UI. This also means the downloading of objects is scriptable if needed downloading objects from the network or the internet

### Feature design description

The O3DE CLI scripts and Project Manager already has the ability to add O3DE repositories and display the available Gems within that repository. The user can then select a Gem to download and register making it available for use in projects. This feature will extend the current Gem Repositories feature to Projects and Templates. This will include extending the Python scripts to support listing the available Projects and Templates and then the ability to download and register a named Project/Template. Following this, changes to Project Manager to be able to list Projects and Templates that are within added repositories and being able to trigger the download and registration of those objects. This should also be able to detect any dependencies and ask the user whether these should be downloaded in order to use the selected object. Since projects are larger for gems the scope of this work also includes the basic ability to attempt to detect and resume incomplete downloads, and have the currently downloading objects in a more accessible location. The priority of this work will be given to downloading projects, but will also cover Templates.

### Technical design description

In order to carry out this work, the following additions/changes to the current remote gem system will be made:
- Editing the functions in scripts/o3de/o3de/download.py to make sure that O3DE objects are downloaded and registered successfully. Generalizing the functions to work for all objects using a filter on type.
- Extend download functionality in scripts/o3de/o3de/util.py to attempt to detect and resume downloads that did not complete.
- Editing the Gem Catalog in Project Manager (Code/Tools/ProjectManager/Source/GemCatalog) to be more generalized. This includes being able to view the Catalog without being in the context of editing a project, and also adding a filter for the O3DE object type, so it can be filtered on Gems/Projects/Templates. When going into the Gem Catalog for a project it should be fixed to filter on Gems.
- Changes to addg additional entry points in Project Manager to register repositories and download objects. For example being able to register a repository from the Projects screen, and also being able to view and download projects from that screen.

An example layout for a repository containing 2 gems and 1 project would be:
```
{
    "repo_name": "RepositoryName",
    "origin": "CreatorName",
    "repo_uri": "http://localhost:8080/",
    "summary": "Example Repository",
    "additional_info": "Example repository hosted on local http server.",
    "gems": [
        "http://localhost:8080/TestGem",
        "http://localhost:8080/TestGem2"
    ],
    "projects": [
        "http://localhost:8080/TestProject"
    ]
}
```

### What are the advantages of the feature?

- Easier set up of any existing O3DE object that has been set up to use this system, removing the need to manually download, extract and register new objects
- Functionality will be implemented in the o3de Python scripts and used in Project Manager so it will be easy to use parts of this for scripting the set up of team members.

### What are the disadvantages of the feature?

If the UI is designed to be different for downloading Projects compared to Gems and templates, this will increase the complexity of the Project Manager.

### How will this be implemented or integrated into the O3DE environment?

This will follow the current remote gems design and be implemented within the Python scripts for the backend, with Project Manager acting as a UI calling python to manage the Repositories and initiating the download and registering of objects.

### Are there any alternatives to this feature?

The alternative other than following the manual steps to register objects, is to just fix the CLI to register these objects. This will be then providing additional scripts and documentation on how to use the functionality to automate the process, however, this still requires more knowledge of the available scripts than using the Project Manager UI.

### How will users learn this feature?

This feature will be announced in the Discord channel (sig-content) and this RFC will be posted to get preliminary notice. Once the feature is submitted, a blog post will be written to properly announce it pointing to how it will solve some common use cases. The blog post will point to documentation to help developers get started.

Documentation will be created detailing how to use the individual functions through Python for scripting, and additional documentation for the UI changes to Project Manager. However for the UI, it should also be able to guide the user through set up without the use of documentation.

### Are there any open questions?

No.

**Comment by byrcolin** [comment]
The engine is currently burdened with o3de objects which are not core to the engine. We need a mechanism for hoisting non-core o3de objects from the core engine repo into one or many external repos.

Currently o3de has an external repo concept, however the design is for static objects, i.e. object that are not in active development. Static objects are “done” and don’t hardly every change. This is mostly appropriate for final asset gems. The asset is “done” and probably wont change at all. This type of static object lends itself to CDN distribution which is why is why they are typically hosted on a web server using HTTP protocol for retrieval which can take advantage of all the edge delivery mechanisms designed to speed up web applications.
The way it works is that a repo.json is linked to the engine in the “repos” list of the engine.json. Ex. 
```
{
  …
    “repos”:[
        “https://www.o3de.org”,
        “ftps://ftp.overlo3de.com”,
        “s3://geo3de”
  ]
}
```
These repo links are such that if you append “repo.json” i.e. https://www.o3de.org/repo.json that file exists and is downloaded and cached for offline use. This file contains all advertisements for o3de objects that o3de.org has on offer. That repo.json lists o3de projects, gems, etc. These objects may be available to download from o3de.org’s own web server or point to some other web/ftp server. So the repo.json just lists them, these can be thought of as advertisements for objects, not the objects themselves. O3de now knows where these objects are. Example 
repo.json
```
{
  …
    “gems”:[
    “https://www.o3de.org/gems/Blast”,
    “https://www.o3de.org/gems/NVCloth”
    ]
} 
```
This says there are 2 gems on offer and since they are gems if I append “gem.json” to the link i.e. https://www.o3de.org/gems/Blast/gem.json that file exists and gets downloaded. This is true for any o3de object not just gems, i.e.
repo.json
```
{
…
  “projects”:[
        “https://www.o3de.org/projects/o3de-atom-sampleviewer”,
    ]
    “gems”:[
        “https://www.o3de.org/gems/Blast”,
        “https://www.o3de.org/gems/NVCloth”
    ],
    “templates”:[
        “http://www.o3de.org/templates/CoolTemplate”
    ]
}
```
This says there is 1 project, 2 gems and 1 template on offer and if I append “template.json” to the link http://www.o3de.org/templates/CoolTemplate i.e. http://www.o3de.org/templates/CoolTemplate/template.json that file exists and is downloaded. The objects json contains all the data o3de needs to display to the user about this object. These advertisements show up alongside local objects when using the o3de CLIor ProgramManager GUI to see available o3de objects. Then when one of these objects on offer is referenced, like a project including a gem which is not yet local, it downloads caches and instances the object in the default folder for that type of object. By default the default folder for a gem is <user>/O3DE/gems folder. Referencing this gem would now find a new folder <user>/O3DE/gems/Blast which would contain the gem.

What we need is a way to specify dynamic o3de objects. i.e. object not yet finished and still in development or are otherwise not finished or never will be “finished”. These dynamic or active development objects will not live on web server or an ftp server or an S3 bucket, but in a online software development platform. By far the most popular ones are git based so that is where we should start. The most popular git based ones on the web are GitHub, GitLab, BitBucket and CodeCommit. It is proposed that repos on these services should be able to be specified as a repo URI so that o3de can download and present it to the user as if it was a static object above. When one of these remote objects is referenced, like when a project enables a gem, that gems git repo is cloned. The objects in these repos can be any o3de object, so an anything from a gem, template, project to even an engine. However this assumption that the “gem.json” appended for a dynamic repo will not work. Instead the python cli will read the item and see if it’s a git repo, if not it will then fall back and assume a static repo in which appending “gem.json” would be appropriate. So the repos would now look like this:
repo.json
```
{
…
    “projects”:[
        “https://github.com/o3de/o3de-atom-sampleviewer.git”,
    ]
    “gems”:[
        “https://github.com/o3de/Blast.git”,
        “https://bitbucket.com/o3de/NVCloth.git”
    ],
    “templates”:[
        “http://www.o3de.org/templates/CoolTemplate”
    ]
}
```
Note that the links are now are the clone repo strings, such that if we would prepend “git clone” i.e. “git clone https://github.com//o3de/o3de-atom-sampleviewer.git” this would clone the git repo. Also Note I purposely left the template line unaltered to show we can mix this approaches. The python would inspect the line item and detect known hosting services like https://github.com ending with “.git” and determine this item lives in a github git repo. Note to I changed NVCloth to live in a BitBucket repo and would be detected the same way. Each of these services has a RAW way to access single files in a repo, which his what we would use to access the o3de json file which describes the object, i.e. the “gem.json” or “project.json”. This would allow us to download the singular file which is a part of the repo without downloading the whole repo. This would be custom per known service. If we detect it is a git repo from an unknown service, as a fall back be could clone it and extract the o3de json file, so the known services would be optimized. Note too that repo.json files will almost always live on a web/ftp/s3 host, not a git repo, but we should support that as well. The danger here is that these services do not want to be general file information services like a web server so they take measures to discourage there use as such by throttling the number of requests per second for RAW data. This can be mitigated by the use of python libraries, like the one GitHub offers, however its an additional python package download which is not bad really, but not all services have them. If we cleverly craft URI then it may work. GitHub is particularly sensitive to this and will the web api will just stop working for minutes leading to a poor user experience. In their documentation they state “if you are crafting URI’s then your doing it wrong”, which is why they make the git python lib. For any of these we can always fall back to cloning the repo.

AR will need a change to make this work. I believe it will consist of a single call to the o3de CLI to download/refresh anything it needs for the current project, if there is one. AR runs the AutomatedTesting project, so the call will initiate a pull on all the needed repos for the engine+project. All canonical objects will be local and available for AR testing. We will most likely want to set different default folders for the build server user as that is where the objects will get downloaded to.

This would allow o3de to hoist o3de objects that are currently in the core engine and in active development to be put into external GitHub repos, the engine simply knows about them and can download on demand when needed. This will dramatically reduce the size of the core engine but will increase the management surface area. The granularity can be down to the o3de object level if need be, and this may be advantageous in some situations, or we could house multiple objects in a single repo much like the engine does currently. Therefore, one repo could contain all the external gems in one link if we wish, the drawback to this is the same as having all these in the engine, unneeded objects will get downloaded, but may be theoretically be easier to manage. I would advocate for object level granularity. We could try having a single repo that is simply a list of sub-modules for convenience perhaps if people think this is a problem, but I don’t anticipate it will be.

This raises an interesting concern, how do know which o3de objects are “real” or “official” and which are community made objects made by whomever. We also want to make this as transparent as possible. So, we need a mechanism to classify some of these external o3de objects as “canonical” meaning it is as though they were included by the core o3de repo and so carries the guarantee that they will be present for all testing and tested as working for a release, but live still live outside the core repo.
They way we handle this will be since it is as though canonical o3de objects are local already, when referenced and not local, will automatically be downloaded, cached and instanced for the user in the default object path for that type of object without prompting/warning, it simply happens. This will keep the experience as transparent as possible to the user. The engine.json “repos” will be replaced by “canonical_repos” list. Partners can have their own canonical repos added via pull request. As a perk of being an o3de partner, only partners will have the ability to have their repos added to the canonical list, which is akin to adding them directly into the engine repo. Everyone gets them by default when they download o3de. Canonical repos are implicitly trusted, the user is not prompted to confirm anything, are automatically downloaded, cached and instanced on reference and the user will be barely even aware it is happening in the background.

This would also allow the contextual hoisting of o3de objects. The o3de engine.json canonical list would have o3des canonical repo.json linked. That repo.json then links to o3df github repos for the gems. Further, AWS has a number of integration gems currently in the engines gems folder. If it’s an AWS gem it should not be in the o3de repo but in an AWS external canonical repo. Only a link to AWS’s canonical repo.json should be in the o3de engine.json’s canonical list. That canonical repo.json should then link to where Amazon wishes to host the gem, probably on S3 or AWS’s Github. Further when other partners, such as Microsoft, wants to add their Azure gems they would do the same, a link to Microsoft’s canonical repo.json would be added to the o3de engine.json canonical list. That repo.json would then link to wherever Microsoft wants to host their sample projects, Azure gems and so on.

O3de objects can refer to other o3de objects, even ones not in their own repo, therefore if a canonical object refers to another o3de object, that object must now also be considered canonical. For example the canonical project AutomatedTesting may refer to gems, therefore any gem it refers to is also a canonical gem because AutomatedTesting is a canonical project.

The mantra here is that an object only contains the objects that are absolutely needed by that object to be successfully configured and built when offline. When we consider this for the core engine object repo this means that the core engine object, which has child o3de objects gems, should only have those gems the engine would fail to configure and build in engine centric no project mode, offline. All other objects can and should be considered ephemeral (or non-core, but still canonical) and are be prime candidates for hoisting into external canonical repos. When we consider the implication of this mantra to projects in the engine, we should come to the conclusion that the engine should have no projects, but links to canonical projects, as the engine can be configured and built in engine centric mode without a project. Since a project can contain child gems as well, they should only contain those gems, or links to gems, it needs to configure and build using an engine. When added, links are deduplicated and circular links are removed. The project has its own canonical list of gem links in its project.json. If the gem is canonical it would not be contained in the project but would have link.

Containing only what is needed is NOT a hard rule, but a guiding principle for o3de. There may be exceptions we wish to make. For example a gem may not be used by the engine without a project, but might be used by every project ever made. This object is not required for the engine to configure and build successfully offline in engine centric mode, however since every project uses it may make sense to simply include it with the engine, however doing so then ties its update cadence inextricably to the engines release cadence, perhaps needlessly. So, we may come to the conclusion that we want this object in the o3de repo even though it may not past the test, which is fine as long as that determination was the result of due consideration by SIG-Core.

Non o3de partners may wish to add their repos to a list that everyone gets, and we should allow this by adding them to a different list, the engine.json’s “noncanonical_repos” list. This list is treated differently than the canonical objects. Whereas the canonical list is implicitly trusted and therefore no prompting of the user is required and everything is automatic, non o3de partner repos are not trusted, not tested, there is no release guarantee implied, no support is to be expected and the user is prompted to confirm they want to download when referenced, and they are reminded of the risks involved in downloading building and executing non-canonical o3de objects. I believe this should motivate non o3de partners, especially ones that have a profit motivation, to become o3de partners.

The end user will also undoubtably want to add random repo URI’s that they want. We should provide the same two lists “canonical_repos” and “noncanonical_repos” lists for them to alter so they do not have to alter the engine.json repo lists as we are aiming to keep the engine repo as immutable. Therefore all such user additions appropriately go in the o3de_manifest.json for that user. These lists will be aggregated with the engine.json’s lists and the active project.json’s lists and function in the same way. If they add a random URI to their o3de_manifest.json canonical list, then it will be implicitly trusted and no prompting will occur. I can see this as useful when team is working on a project and don’t need all the scare warnings for their own code. If they add the random repo link to the noncanonical list it will be untrusted and prompting/reminders/warnings will occur, the user makes that choice for themselves.
<user>/O3DE/manifest.json
```
{
    …
    “canonical_repos”:[ 
        “https://www.byrcolin.net/o3de”,
        “https://aws.amazon.com/newworld”,
        “https://aws.amazon.com/newworld/tests”,
        “https://aws.amazon.com/portabello/characters”
    ],
    “noncanonical_repos”:[
        “https://crazy.io/o3de/free/characters”	
    ]	
}
```
Once such a system is in place it will function effectively as a decentralized o3de store, full of community objects for people to download and play with. We will add a new fields to the o3de json schema to support whether or not the user is currently “entitled” to an object. Community members/partners with a profit motivation may use this system as the basis on which they design and implement a pay for object store. We can encode the login:password@server into the repo URI. The web server would receive this information and dynamically generate a repo.json for that user which contains links to objects they have bought, in which the o3de json file will have “entitled”: True, for o3de object bought from that store. These objects would show up along side all the other community objects. When a reference to an object with “entitled”:False, we pop up a web browser to the root URI. Then the user can login, pay for the object, which will set “entitled”:True in that objects json, which tells the object to try to download. To enhance discovery the ProgramManger would show both bought and unbought items. We could color the o3de item which are “entitled”:False as red or something to indicate they are not entitled to that object yet. We could put a filter in place for these repos so that a user could filter there view to only objects from that repo.
http://www.forprofitstore.com/byrcolin/o3de/gems/spaceship/gem.json 
{
    "gem_name": " spaceship ",
    "display_name": " spaceship ",
    "license": "Some not free license",
    "license_url": " http://www.forprofitstore.com/LICENSE.txt",
    "origin": " forprofitstore llc",
    "origin_url": " http://www.forprofitstore.com/byrcolin/o3de/gems/spaceship ",
    "type": "Asset",
    "summary": "This is a really cool spaceship model you can buy :) .",
    "canonical_tags": [
        "Gem"
    ],
    "user_tags": [
        "Spaceship”
    ],
    "icon_path": "spaceship.png",
    "requirements": "",
    "documentation_url": "",
    "dependencies": [],
    "entitlement": false
}
This is a model of space ship for sale on forprofitstore.com. The “entitlement”: false lets o3de know they do not own this yet, so if they try to make a reference to it, it will not succeed, as it will fail to download. So instead of enabling the gem it would pop a browser to the link provided. This gem.json is generated by the store web server for me, and because my byrcolin user does not own this gem yet, the server added “entitlement”: false. This information is presented to the user, that its not free. And will warn the user on attempting to enable the gem that I don’t own this gem and confirm I want to open the provided store page, showing the link I would goto. If I agree it pops the web browser to that page. The user does whatever they need to do on the site to buy it. The gem.json is refreshed in the cache and now the "entitlement": false -> is "entitlement": true (or just not there). The web server then allows me to download it, or adds me to a permissions list so that I can now see it in GitHub or whatever.

Another question here is should we allow direct linking in the object json lists? I think so…
engine.json
```
{
    …
    “canonical_repos”:[
        “https://www.o3de.org”,
        “https://aws.amazon.com/o3de”,
        “https://www.microsoft.com/o3de”,
        “https://nianticlabs.com/o3de”,
        “https://www.tencent.com/o3de”,
        “https://www.huawei.com/o3de”,
        “https://www.adobe.com/o3de”,
        “https://www.intel.com/o3de”,
        “https://www.audiokinetic.com/o3de”,
        “https://www.redhat.com/o3de”,
        “https://igda.org/o3de”,
        “https://accelbyte.io/o3de”,
        “https://backtrace.io/o3de”,
        “https://www.kythera.ai/o3de”,
        “https://kitbash3d.com/o3de”,
        “https://www.sidefx.com/o3de”
    ],
    “noncanonical_repos”:[
        “https://www.overlo3de.com”,
        “https://www.geo3de.com”,
        “https://free3d.com/o3de”,
        “https://www.johnballow.net/funstuff/share/o3de”,
    ]	
}
```
These are all web server/ftp/s3 links, which is what we would expect for because we want to append “repo.json” and download the file. A good question here is should we always assume that the line entries in a object json’s canonical and non-canonical list ALWAYS points to a repo.json? Should we support direct links? i.e.
engine.json
```
{
    …
    “canonical_repos”:[
        https://github.com/o3de/o3de-atom-sampleviewer.git
    ]
}
```

**Comment by AMZN-Phil** [comment]
Having a list of repos under canonical_repos in this case should not skip the entire flow that we use for other objects even if just purely for licensing reasons. If one of the repositories from a partner for example contains a Gem that has a proprietary/non-standard license, and someone downloads a project that has that Gem as a dependency, they would expect to be informed before that is downloaded/instanced/registered on their machine. 

This work will also cover being able to add a repository that is a cloneable GitHub link (once everything is running we could expand this to other services, the APIs are even very similar in the others listed), though as we would still be requiring a repo.json, at least initially as a first step in this direction, even if it is external to the GitHub repository and points to the object in the GitHub repo. We are expecting to use the GitHub API to get access to file contents for this (not using direct links). However, we're still going to have to cope with a low rate limit initially due to GitHub also capping use of API requests from non-authenticated users, and authentication is outside the scope of this initial work to expand to other o3de object types.

**Comment by byrcolin** [comment]
I see. The licensing issue is interesting. I agree. Maybe what we should do is allow the user to configure which license type will trigger the prompting. The we ship o3de with by default with MIT and Apache 2 and other known permissive licenses pre-populated. We would then always check the license on the object to be in that list, if not prompt. That way it give the user control and on a build server we just give a * to accept all license's as all canonical objects need to be local for AR.

**Comment by AMZN-Phil** [comment]
The current idea for this is to have a allow list of permissive licenses, if the user wants to downloads an object or one will be pulled in as a dependency that has a license in the allow list we could choose to not surface that to the user, for other licenses this is displayed as additional information to the user before they commence the download. We could add a way for users to exclude repositories from this check though, either through another repositories list in the manifest, a settings file or some other means, to avoid teams from having these warnings for code they have developed.

We will be implementing linking to git repos, just that they will be linked from a repo.json as an object as in your earlier example

```
{
...
    “projects”:[
        “https://github.com/o3de/o3de-atom-sampleviewer.git”,
    ]
}
```

Having direct links is something that would fall after this initial work.

**Comment by byrcolin** [comment]
Ok. Needing the repo.json could be a sticking point for users as it requires an http/ftp/s3 to host the file... I'm not crazy about hosting the repo.json in a git repo... like we could have a repo with only that file in it and download it that way. That would make it easier, since they wouldn't have to have a server and the list could be controlled via PR. What are your thoughts on that?

**Comment by AMZN-Phil** [comment]
For authentication this is something that is slightly different per service. For GitHub we have the option of using a personal access token or using OAuth. Both need some further investigation, since we'll be directly managing a user's personal access token or have a registered app that we have a client secret for. This is something we will need after this is implemented though, since once the amount of repositories increase it'll be easier to hit the rate limit. Once this is done this will also give us the benefit of being able to access private repos.

> Ok. Needing the repo.json could be a sticking point for users as it requires an http/ftp/s3 to host the file... I'm not crazy about hosting the repo.json in a git repo... but it might be a very popular way to do it. like we could have a repo with only that file in it and download it that way. That would make it easier, since they wouldn't have to have a server and the list could be controlled via PR. What are your thoughts on that? I might be difficult to determine if it is a repo.json git or a direct link...
> Ok. Needing the repo.json could be a sticking point for users as it requires an http/ftp/s3 to host the file... Thats why I was thinking maybe direct link would solve some of that pain. Maybe hosting the repo.json in a git repo... might be a way to do it. Like the user could create a repo with only a repo.json file in it and download/clone it that way. That would potentialy make it easier, since they wouldn't have to have a server and the list could be controlled via PR. What are your thoughts on that?
> 
> ```
> {
>     …
>     “canonical_repos”:[
>         https://github.com/o3de/o3de-atom-sampleviewer.git
>     ]
> }
> ```
> 
> Might be difficult to determine if this is a repo.json git or a direct link... unless we are never planning on direct linking from the repos lists. This is probably the best argument against direct links :) If its a git then we know its a repo we get through the api or clone and read it.

I would be good with supporting something like this. We would probably want to attempt to use the API to access the repo.json file first anyway in case someone attempts to add a large repo and we sync the entire thing just to find it's missing the small manifest file we were looking for. That wouldn't completely close the door on a direct link later if we wanted to go that route since we'll be starting with the validation for repo.json which could be replaced/removed later.

**Comment by AMZN-alexpete** [comment]
For Git repos we can do a shallow clone + sparse checkout cone mode in a temp folder and just grab the files in the root to get whatever object json file we need.  

```
# shallow partial clone (about 1mb)
git clone --filter=blob:none --no-checkout --depth=1 https://github.com/o3de/o3de o3de-sparse-partial
cd o3de-sparse-partial

# get one file - might have to run this twice, I got an error the first time about a sha error
git checkout development -- README.md

# alternately instead of git checkout you might be able to just look at the contents of the file by first getting the sha with ls-tree
git ls-tree HEAD <filename>
100644 blob <sha> <filename>

# then dump the output of the file with git cat-file. Note the first time this runs it might include git output about receiving the object, will need some testing.
git cat-file -p <sha>
```


If Git authentication is required, the OS should pop-up a login window where they can enter credentials, so Project Manager shouldn't need to be involved except to let the user know if authentication fails and access is denied.

**Comment by lsemp3d** [comment]
Moving to final review period, expected to close by 5/12

**Comment by Ulrick28** [comment]
It is 5/12, is this still scheduled to close today?

**Comment by monroegm** [comment]
Approved on 5/18. @AMZN-Phil please commit this to the [repo](https://github.com/o3de/sig-content/tree/main/rfcs) as rfc-54.
